import "dotenv/config";
import bcrypt from "bcryptjs";
import { connectDB } from "../config/db.js";
import Artist from "../models/Artist.js";
import Event from "../models/Event.js";
import Booking from "../models/Booking.js";
import User from "../models/User.js";

const artists=[
{name:"Arjun Mehta",stageName:"Arjun Mehta",avatar:"https://i.pravatar.cc/150?img=12",genres:["Indie","Acoustic","Singer-Songwriter"],location:"Mumbai",bio:"Warm acoustic sets blending indie originals with familiar crowd favourites.",experience:6,fee:35000,rating:4.8,reviews:86,tags:["Acoustic","Intimate","Originals"],availability:["2026-09-15","2026-09-20","2026-09-25"]},
{name:"Maya Collective",stageName:"Maya Collective",avatar:"https://i.pravatar.cc/150?img=32",genres:["Indie","Pop","Soul"],location:"Mumbai",bio:"Four-piece live act built for intimate venues, brand events and weddings.",experience:8,fee:48000,rating:4.9,reviews:121,tags:["Live Band","Soul","Pop"],availability:["2026-09-15","2026-09-18","2026-09-22"]},
{name:"Rohan Kapoor",stageName:"Rohan Kapoor",avatar:"https://i.pravatar.cc/150?img=53",genres:["Electronic","House","Ambient"],location:"Bengaluru",bio:"Electronic producer and live performer for modern cultural and nightlife events.",experience:5,fee:42000,rating:4.7,reviews:64,tags:["Electronic","DJ","Live"],availability:["2026-09-15","2026-09-25"]},
{name:"The Acoustic Project",stageName:"The Acoustic Project",avatar:"https://i.pravatar.cc/150?img=14",genres:["Acoustic","Folk","Indie"],location:"Pune",bio:"Acoustic duo known for relaxed folk and indie performances.",experience:7,fee:28000,rating:4.6,reviews:51,tags:["Duo","Folk","Acoustic"],availability:["2026-09-15","2026-09-22"]},
{name:"Sara Fernandes",stageName:"Sara Fernandes",avatar:"https://i.pravatar.cc/150?img=47",genres:["Jazz","Soul","Acoustic"],location:"Mumbai",bio:"Jazz and soul vocalist for premium dinners, weddings and curated events.",experience:10,fee:55000,rating:4.9,reviews:143,tags:["Jazz","Premium","Vocalist"],availability:["2026-09-17","2026-09-25"]},
{name:"Kabir & Co.",stageName:"Kabir & Co.",avatar:"https://i.pravatar.cc/150?img=68",genres:["Rock","Indie","Alternative"],location:"Mumbai",bio:"High-energy alternative rock group for festivals and larger event stages.",experience:9,fee:65000,rating:4.7,reviews:78,tags:["Rock","Festival","Band"],availability:["2026-09-15","2026-09-28"]},
{name:"Naina Rao",stageName:"Naina Rao",avatar:"https://i.pravatar.cc/150?img=44",genres:["Bollywood","Pop","Acoustic"],location:"Mumbai",bio:"Versatile vocalist with a polished Bollywood and pop repertoire.",experience:5,fee:32000,rating:4.8,reviews:95,tags:["Bollywood","Pop","Vocalist"],availability:["2026-09-15","2026-09-19"]},
{name:"Dev Malhotra",stageName:"Dev Malhotra",avatar:"https://i.pravatar.cc/150?img=59",genres:["Folk","Indie","Acoustic"],location:"Goa",bio:"Independent folk artist with a relaxed sound suited to intimate cultural spaces.",experience:4,fee:24000,rating:4.5,reviews:38,tags:["Folk","Solo","Indie"],availability:["2026-09-15","2026-09-30"]}
,{name:"Aisha Khan",stageName:"Aisha Khan",avatar:"https://i.pravatar.cc/150?img=25",genres:["Stand-up Comedy","Comedy","Storytelling"],location:"Delhi",bio:"Sharp observational stand-up and storytelling for comedy nights, corporate shows and private events.",experience:7,fee:30000,rating:4.8,reviews:72,tags:["Stand-up","Comedy","Corporate"],availability:["2026-09-15","2026-09-18","2026-09-24"]}
,{name:"Open Mic Collective",stageName:"Open Mic Collective",avatar:"https://i.pravatar.cc/150?img=11",genres:["Open Mic","Poetry","Acoustic","Spoken Word"],location:"Bengaluru",bio:"Curated open-mic collective featuring poetry, acoustic music and spoken-word performers.",experience:6,fee:26000,rating:4.6,reviews:49,tags:["Open Mic","Poetry","Spoken Word"],availability:["2026-09-15","2026-09-21","2026-09-26"]}
,{name:"DJ Veer",stageName:"DJ Veer",avatar:"https://i.pravatar.cc/150?img=61",genres:["DJ","Clubbing","House","Electronic"],location:"Goa",bio:"High-energy DJ specialising in club nights, destination parties and festival sets.",experience:9,fee:60000,rating:4.9,reviews:118,tags:["DJ","Club","House","Festival"],availability:["2026-09-15","2026-09-19","2026-09-27"]}
,{name:"Karan Sethi",stageName:"Karan Sethi",avatar:"https://i.pravatar.cc/150?img=70",genres:["Celebrity Appearance","Bollywood","Public Speaking"],location:"Mumbai",bio:"Celebrity guest and public speaker available for brand launches, college events and premium appearances.",experience:11,fee:120000,rating:4.9,reviews:164,tags:["Celebrity","Guest","Brand"],availability:["2026-09-20","2026-09-25","2026-09-30"]}
];
async function seed(){await connectDB(); await Booking.deleteMany({}); await Event.deleteMany({}); await User.deleteMany({}); await Artist.deleteMany({}); const inserted=await Artist.insertMany(artists); const manager=await User.create({name:'Muzammil Khan',email:'manager@dreamstage.com',passwordHash:await bcrypt.hash('password123',12),role:'EVENT_MANAGER'}); const passwordHash=await bcrypt.hash('password123',12); const artistEmails=['arjun@dreamstage.com','maya@dreamstage.com','rohan@dreamstage.com','acoustic@dreamstage.com','sara@dreamstage.com','kabir@dreamstage.com','naina@dreamstage.com','dev@dreamstage.com','aisha@dreamstage.com','openmic@dreamstage.com','djveer@dreamstage.com','karan@dreamstage.com']; const artistUsers=await User.insertMany(inserted.map((a,i)=>({name:a.name,email:artistEmails[i],passwordHash,role:'ARTIST',artist:a._id}))); await Event.create({createdBy:manager._id,title:'Mumbai Indie Night',type:'Music Event',location:'Mumbai',date:'2026-09-15',budget:50000,genre:'Indie',duration:'2 hours',description:'An intimate evening celebrating independent Indian artists.',startTime:'19:30',status:'OPEN'}); console.log('Seeded. Manager: manager@dreamstage.com / password123'); console.log('Artist: arjun@dreamstage.com / password123'); process.exit(0)} seed().catch(e=>{console.error(e);process.exit(1)});
